# Application Settings
spring.application.name=DHA
server.port=9090

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Eclaim
spring.datasource.username=postgres
spring.datasource.password=Eoxys@110
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Custom Properties
eclaim.endpoint.url=https://webhook.site/bee21429-76f1-4b47-bff9-3ef8ce5ea196